# Generated by Django 4.2 on 2026-04-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('field_worker', 'Field Worker'), ('irrigation_worker', 'Irrigation Worker'), ('equipment_operator', 'Equipment Operator'), ('supervisor', 'Supervisor'), ('farm_manager', 'Farm Manager')], max_length=50),
        ),
    ]
