# Generated by Django 5.2.11 on 2026-03-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_sol', models.CharField(choices=[('argileux', 'Argileux'), ('sableux', 'Sableux'), ('limoneux', 'Limoneux'), ('calcaire', 'Calcaire'), ('humifere', 'Humifère'), ('autre', 'Autre')], max_length=30)),
                ('culture_plantee', models.CharField(choices=[('ble', 'Blé'), ('mais', 'Maïs'), ('orge', 'Orge'), ('pomme_de_terre', 'Pomme de terre'), ('tomate', 'Tomate'), ('olive', 'Olive'), ('aucune', 'Aucune'), ('autre', 'Autre')], default='aucune', max_length=30)),
                ('localisation', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
