# Generated by Django 5.2.8 on 2026-04-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_parcelle_latitude_parcelle_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='moisture',
            field=models.IntegerField(default=71),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='nitrogen',
            field=models.IntegerField(default=42),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='ph',
            field=models.DecimalField(decimal_places=2, default=6.8, max_digits=4),
        ),
    ]
