services:
  - type: web
    name: agritech-api
    env: python
    plan: free
    buildCommand: cd services/equipment_service && pip install -r requirements.txt && python manage.py migrate
    startCommand: cd services/equipment_service && gunicorn agri_equipment_service.wsgi:application --bind 0.0.0.0:10000
