# Generated by Django 5.2.12 on 2026-04-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FARM_MANAGER', 'Farm Manager'), ('SUPERVISOR', 'Supervisor'), ('FIELD_WORKER', 'Field Worker'), ('IRRIGATION_WORKER', 'Irrigation Worker'), ('EQUIPMENT_OPERATOR', 'Equipment Operator'), ('AGRONOMIST', 'Agronomist'), ('QUALITY_INSPECTOR', 'Quality Inspector')], default='FIELD_WORKER', max_length=20),
        ),
    ]
