# Generated by Django 5.2.8 on 2026-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farm_manager', 'Farm Manager'), ('supervisor', 'Supervisor'), ('agronomist', 'Agronomist'), ('quality_inspector', 'Quality Inspector'), ('field_worker', 'Field Worker'), ('irrigation_worker', 'Irrigation Worker'), ('equipment_operator', 'Equipment Operator')], default='field_worker', max_length=20),
        ),
    ]
