# Generated by Django 6.0.4 on 2026-04-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'équipement")),
                ('type', models.CharField(max_length=50, verbose_name="Type d'équipement")),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de série')),
                ('usage_hours', models.IntegerField(default=0, verbose_name="Heures d'utilisation")),
                ('status', models.CharField(choices=[('operational', 'Opérationnel'), ('maintenance', 'En maintenance'), ('broken', 'Cassé'), ('retired', 'Retiré')], default='operational', max_length=20, verbose_name='Statut')),
                ('last_revision', models.DateField(blank=True, null=True, verbose_name='Dernière révision')),
                ('next_revision', models.DateField(blank=True, null=True, verbose_name='Prochaine révision')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
    ]
